#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM23:PHI    0
caput BEAM:CBREM:DIAM23:THETA  0
caput BEAM:CBREM:DIAM23:PHI0   0
caput BEAM:CBREM:DIAM23:PHI022 45
caput BEAM:CBREM:DIAM23:OFF_PITCH  0
caput BEAM:CBREM:DIAM23:OFF_YAW    0
caput BEAM:CBREM:DIAM23:PARA_YAW    2
caput BEAM:CBREM:DIAM23:PARA_PITCH  0.1
caput BEAM:CBREM:DIAM23:PERP_YAW    1
caput BEAM:CBREM:DIAM23:PERP_PITCH  -0.3
caput BEAM:CBREM:DIAM23:PARA_MODE   1
caput BEAM:CBREM:DIAM23:PERP_MODE   2
