#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM1:PHI    0
caput BEAM:CBREM:DIAM1:THETA  0
caput BEAM:CBREM:DIAM1:PHI0   0
caput BEAM:CBREM:DIAM1:PHI022 45
caput BEAM:CBREM:DIAM1:OFF_PITCH  0.29
caput BEAM:CBREM:DIAM1:OFF_YAW    2.08
caput BEAM:CBREM:DIAM1:PARA_YAW    -0.187462
caput BEAM:CBREM:DIAM1:PARA_PITCH  1.97791
caput BEAM:CBREM:DIAM1:PERP_YAW    -0.0123223
caput BEAM:CBREM:DIAM1:PERP_PITCH  -1.14647
caput BEAM:CBREM:DIAM1:PARA_MODE   4
caput BEAM:CBREM:DIAM1:PERP_MODE   3
