#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM1:PHI    0
caput BEAM:CBREM:DIAM1:THETA  0
caput BEAM:CBREM:DIAM1:PHI0   0
caput BEAM:CBREM:DIAM1:PHI022 45
caput BEAM:CBREM:DIAM1:OFF_PITCH  1.87
caput BEAM:CBREM:DIAM1:OFF_YAW    2.73
caput BEAM:CBREM:DIAM1:PARA_YAW    1.78414
caput BEAM:CBREM:DIAM1:PARA_PITCH  3.04414
caput BEAM:CBREM:DIAM1:PERP_YAW    1.77
caput BEAM:CBREM:DIAM1:PERP_PITCH  2.67
caput BEAM:CBREM:DIAM1:PARA_MODE   3
caput BEAM:CBREM:DIAM1:PERP_MODE   4
