#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM1:PHI    0
caput BEAM:CBREM:DIAM1:THETA  0
caput BEAM:CBREM:DIAM1:PHI0   0
caput BEAM:CBREM:DIAM1:PHI022 0
caput BEAM:CBREM:DIAM1:OFF_PITCH  0
caput BEAM:CBREM:DIAM1:OFF_YAW    0
caput BEAM:CBREM:DIAM1:PARA_YAW    -0.087
caput BEAM:CBREM:DIAM1:PARA_PITCH  2.053
caput BEAM:CBREM:DIAM1:PERP_YAW    3.01
caput BEAM:CBREM:DIAM1:PERP_PITCH  2.416
caput BEAM:CBREM:DIAM1:PARA_MODE   1
caput BEAM:CBREM:DIAM1:PERP_MODE   1
