#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM1:PHI    0
caput BEAM:CBREM:DIAM1:THETA  0
caput BEAM:CBREM:DIAM1:PHI0   0
caput BEAM:CBREM:DIAM1:PHI022 45
caput BEAM:CBREM:DIAM1:OFF_PITCH  1.85
caput BEAM:CBREM:DIAM1:OFF_YAW    2.74
caput BEAM:CBREM:DIAM1:PARA_YAW    0.619792
caput BEAM:CBREM:DIAM1:PARA_PITCH  4.27979
caput BEAM:CBREM:DIAM1:PERP_YAW    0.612721
caput BEAM:CBREM:DIAM1:PERP_PITCH  -0.422721
caput BEAM:CBREM:DIAM1:PARA_MODE   3
caput BEAM:CBREM:DIAM1:PERP_MODE   4
