#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM1:PHI    0
caput BEAM:CBREM:DIAM1:THETA  0
caput BEAM:CBREM:DIAM1:PHI0   0
caput BEAM:CBREM:DIAM1:PHI022 45
caput BEAM:CBREM:DIAM1:OFF_PITCH  1.84
caput BEAM:CBREM:DIAM1:OFF_YAW    0.76
caput BEAM:CBREM:DIAM1:PARA_YAW    0.607289
caput BEAM:CBREM:DIAM1:PARA_PITCH  1.85329
caput BEAM:CBREM:DIAM1:PERP_YAW    0.647
caput BEAM:CBREM:DIAM1:PERP_PITCH  1.756
caput BEAM:CBREM:DIAM1:PARA_MODE   4
caput BEAM:CBREM:DIAM1:PERP_MODE   3
