#!/bin/sh
#Script to push the current settings to the defaults for trhe installed diamond 
#and save to the diamond init script
#source the epics env to get the pathe to caget etc.
. /opt/epics/thisEPICS.sh


if [ $# -ne "2" ] && [ $# -ne "3" ] ; then
    echo
    echo "Usage: $0 <P> <G> <plane>"
    echo "       P and G are the EPICS macros for goni and cbrem. Eg. HD:CBREM: HD:GONI:";
    echo "       <plane> is optional must be 1 or 2 (1=PARA 2=PERP)";
    echo "       If plane is not given, use the currently set plane freom EPICS";
fi

P=$1;
G=$2;


if [ $# = "3" ]; then           #plane on input arg
    plane=$3;
    if [ $plane != "1" ] && [ $plane != "2" ]; then      #1=PARA, 2=PERP
	#pop up warning essage
	warning="UNKNOWN PLANE ( $plane ). Plane must be 1 or 2 (1=PARA, 2=PERP)";
	if ! zenity --title="Adjust coherent bremsstrahlung conditions" --question --text "$warning" --width 650 --height 100; then
	    exit;
	fi
	exit;
    fi;
else                            #plane from EPICS
    plane=`caget -t "${P}PLANE"`;
    if [ $plane = "0" ]; then                           #undefined
	warning="Current plane is unknown. Use Force PARA or Force PERP buttons on Expert GUI (if you know what you're doing";
	if ! zenity --title="Adjust coherent bremsstrahlung conditions" --question --text "$warning" --width 650 --height 100; then
	    exit;
	fi
	exit;
    fi
fi
	
#get YAW and PITCH and push them to update PARA or PERP settings as required.
yaw=`caget -t "${G}YAW"`
pitch=`caget -t "${G}PITCH"`

id=`caget -t "${G}RADIATOR_ID"`;

if [ $plane = "1" ]; then
    caput ${P}PARA_YAW $yaw;   
    caput ${P}PARA_PITCH $pitch;   
    caput ${P}DIAM${id}:PARA_YAW    $yaw;
    caput ${P}DIAM${id}:PARA_PITCH  $pitch;
fi

if [ $plane = "2" ]; then
    caput ${P}PERP_YAW $yaw;   
    caput ${P}PERP_PITCH $pitch;   
    caput ${P}DIAM${id}:PERP_YAW    $yaw;
    caput ${P}DIAM${id}:PERP_PITCH  $pitch;
fi


phi=`caget -t "${P}PHI"`;
theta=`caget -t "${P}THETA"`;
phi0=`caget -t "${P}PHI0"`;
phi022=`caget -t "${P}PHI022"`;
off_pitch=`caget -t "${P}OFF_PITCH"`;  
off_yaw=`caget -t "${P}OFF_YAW"`;

para_yaw=`caget -t "${P}PARA_YAW"`;   
para_pitch=`caget -t "${P}PARA_PITCH"`; 
perp_yaw=`caget -t "${P}PERP_YAW"`;
perp_pitch=`caget -t "${P}PERP_PITCH"`;
para_mode=`caget -t "${P}PARA_MODE"`;
perp_mode=`caget -t "${P}PERP_MODE"`;


caput ${P}DIAM${id}:PHI    $phi;
caput ${P}DIAM${id}:THETA  $theta;
caput ${P}DIAM${id}:PHI0   $phi0;
caput ${P}DIAM${id}:PHI022 $phi022;
caput ${P}DIAM${id}:OFF_PITCH  $off_pitch;
caput ${P}DIAM${id}:OFF_YAW    $off_yaw;

caput ${P}DIAM${id}:PARA_MODE   $para_mode;
caput ${P}DIAM${id}:PERP_MODE   $perp_mode;


thisdate=`date '+%d_%m_%y:%H_%M'`

script="${HOME}/cbrem/data/diamond${id}.sh";
mkdir -p ${HOME}/cbrem/data/backups;

oldscript="${HOME}/cbrem/data/backups/diamond${id}_${thisdate}.sh";

if [ -e ${script} ]; then
    /bin/mv ${script} ${oldscript};
fi


echo "#!/bin/sh" > ${script}
echo "#This file is automatically generated by running the command ${HOME}/cbrem/scripts/saveCurrentDiamondSettings.sh <P>" >> ${script}
echo "#" >> ${script};
echo "#" >> ${script};

echo "caput ${P}DIAM${id}:PHI    $phi" >> ${script};
echo "caput ${P}DIAM${id}:THETA  $theta" >> ${script};
echo "caput ${P}DIAM${id}:PHI0   $phi0" >> ${script};
echo "caput ${P}DIAM${id}:PHI022 $phi022" >> ${script};
echo "caput ${P}DIAM${id}:OFF_PITCH  $off_pitch" >> ${script};
echo "caput ${P}DIAM${id}:OFF_YAW    $off_yaw" >> ${script};

echo "caput ${P}DIAM${id}:PARA_YAW    $para_yaw" >> ${script};
echo "caput ${P}DIAM${id}:PARA_PITCH  $para_pitch" >> ${script};
echo "caput ${P}DIAM${id}:PERP_YAW    $perp_yaw" >> ${script};
echo "caput ${P}DIAM${id}:PERP_PITCH  $perp_pitch" >> ${script};
echo "caput ${P}DIAM${id}:PARA_MODE   $para_mode" >> ${script};
echo "caput ${P}DIAM${id}:PERP_MODE   $perp_mode" >> ${script};

chmod +x ${script};
