#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:PHI    0
caput BEAM:CBREM:THETA  0
caput BEAM:CBREM:PHI0   0
caput BEAM:CBREM:PHI022 45
caput BEAM:CBREM:OFF_PITCH  1.85
caput BEAM:CBREM:OFF_YAW    2.74
caput BEAM:CBREM:PARA_YAW    0.74
caput BEAM:CBREM:PARA_PITCH  4.4
caput BEAM:CBREM:PERP_YAW    0.74
caput BEAM:CBREM:PERP_PITCH  -0.55
caput BEAM:CBREM:PARA_MODE   3
caput BEAM:CBREM:PERP_MODE   4
