#!/bin/sh
#This file is automatically generated by running the command /home/a2cb/cbrem/scripts/saveCurrentDiamondSettings.sh <P>
#
#
caput BEAM:CBREM:DIAM:PHI    
caput BEAM:CBREM:DIAM:THETA  
caput BEAM:CBREM:DIAM:PHI0   
caput BEAM:CBREM:DIAM:PHI022 
caput BEAM:CBREM:DIAM:OFF_PITCH  
caput BEAM:CBREM:DIAM:OFF_YAW    
caput BEAM:CBREM:DIAM:PARA_YAW    
caput BEAM:CBREM:DIAM:PARA_PITCH  
caput BEAM:CBREM:DIAM:PERP_YAW    
caput BEAM:CBREM:DIAM:PERP_PITCH  
caput BEAM:CBREM:DIAM:PARA_MODE   
caput BEAM:CBREM:DIAM:PERP_MODE   
